
package visao;

import controle.Emprestimos;
import entidade.DAOemprestimos;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;


public class CadEmprestimos extends javax.swing.JFrame {
    
    Emprestimos em =new Emprestimos();
    DAOemprestimos dao= new DAOemprestimos();

    public CadEmprestimos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRsim = new javax.swing.JRadioButton();
        jRnao = new javax.swing.JRadioButton();
        jTcliente = new javax.swing.JTextField();
        jTlivro = new javax.swing.JTextField();
        jTdataemprestimos = new javax.swing.JTextField();
        jTdatadevolucao = new javax.swing.JTextField();
        jBregistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 51, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Cadastrar Emprestimo");

        jLabel2.setText("Id Cliente:");

        jLabel3.setText("Id Livro:");

        jLabel4.setText("Data de Emprestimo:");

        jLabel5.setText("Data de Devolução:");

        jLabel6.setText("Devolução:");

        buttonGroup1.add(jRsim);
        jRsim.setText("Sim");
        jRsim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRsimActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRnao);
        jRnao.setText("Não");

        jTlivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTlivroActionPerformed(evt);
            }
        });

        jBregistrar.setText("Registrar");
        jBregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jBregistrar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRsim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRnao))
                            .addComponent(jTlivro, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jTcliente)
                            .addComponent(jTdataemprestimos)
                            .addComponent(jTdatadevolucao)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTlivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTdataemprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTdatadevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jRsim)
                    .addComponent(jRnao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jBregistrar)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregistrarActionPerformed
        String formato = "dd/MM/yyyy";
        if(jTcliente.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Obrigatorio!");
            jTcliente.requestFocus();
        } else if (jTlivro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Campo obrigatório!");
            jTlivro.requestFocus();
        } else if (jTdataemprestimos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Campo obrigatório!");
            jTdataemprestimos.requestFocus();
        } else if (jTdatadevolucao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Campo obrigatório!");
            jTdatadevolucao.requestFocus();
        } else if (!validarFormatoData(jTdataemprestimos.getText(),formato)) { 
            JOptionPane.showMessageDialog(rootPane, "Formato de data inválido, tente dd/MM/yyyy!");
            jTdataemprestimos.requestFocus();
        } else if (!validarFormatoData(jTdatadevolucao.getText(),formato)) {
            JOptionPane.showMessageDialog(rootPane, "Formato de data inválido, tente dd/MM/yyyy!");
            jTdatadevolucao.requestFocus();
        }else{
            try {
                em.setId_leitor(Integer.parseInt(jTcliente.getText()));
                em.setId_livro(Integer.parseInt(jTlivro.getText()));

                em.setData_emprestimo(jTdataemprestimos.getText());
                em.setData_devolucao(jTdatadevolucao.getText());                
                
                if(jRsim.isSelected()){
                    em.setDevolucao("SIM");
                } else if(jRnao.isSelected()){
                    em.setDevolucao("NAO");
                }
                
                dao.inserir(em);
            } catch (Exception ex) {
                //Logger.getLogger(CadLivro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBregistrarActionPerformed

    private void jTlivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTlivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTlivroActionPerformed

    private void jRsimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRsimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRsimActionPerformed
    
    private boolean validarFormatoData(String data, String formato) {
        String regex = "\\d{2}/\\d{2}/\\d{4}";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(data);

        return matcher.matches();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadEmprestimos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBregistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRnao;
    private javax.swing.JRadioButton jRsim;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTcliente;
    private javax.swing.JTextField jTdatadevolucao;
    private javax.swing.JTextField jTdataemprestimos;
    private javax.swing.JTextField jTlivro;
    // End of variables declaration//GEN-END:variables

}
