
package visao;

import javax.swing.JFrame;

public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBcadastrarleitor = new javax.swing.JButton();
        jBlistarleitor = new javax.swing.JButton();
        jBDeletarleitor = new javax.swing.JButton();
        jBeditarleitor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBcadastrarlivro = new javax.swing.JButton();
        jBeditarlivro = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jBlistarlivro = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jBcadastrarEm = new javax.swing.JButton();
        jBlistarem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBcadastrarleitor.setText("Cadastrar Leitor");
        jBcadastrarleitor.setMaximumSize(new java.awt.Dimension(100, 23));
        jBcadastrarleitor.setMinimumSize(new java.awt.Dimension(100, 23));
        jBcadastrarleitor.setPreferredSize(new java.awt.Dimension(100, 23));
        jBcadastrarleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarleitorActionPerformed(evt);
            }
        });

        jBlistarleitor.setText("Listar Leitor");
        jBlistarleitor.setMaximumSize(new java.awt.Dimension(100, 23));
        jBlistarleitor.setMinimumSize(new java.awt.Dimension(100, 23));
        jBlistarleitor.setPreferredSize(new java.awt.Dimension(100, 23));
        jBlistarleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlistarleitorActionPerformed(evt);
            }
        });

        jBDeletarleitor.setText("Deletar Leitor");
        jBDeletarleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeletarleitorActionPerformed(evt);
            }
        });

        jBeditarleitor.setText("Editar Leitor");
        jBeditarleitor.setMaximumSize(new java.awt.Dimension(100, 23));
        jBeditarleitor.setMinimumSize(new java.awt.Dimension(100, 23));
        jBeditarleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeditarleitorActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 51, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Leitor");

        jLabel2.setBackground(new java.awt.Color(0, 51, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Livros");

        jBcadastrarlivro.setText("Cadastrar Livro");
        jBcadastrarlivro.setMaximumSize(new java.awt.Dimension(100, 23));
        jBcadastrarlivro.setMinimumSize(new java.awt.Dimension(100, 23));
        jBcadastrarlivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarlivroActionPerformed(evt);
            }
        });

        jBeditarlivro.setText("Editar Livro");
        jBeditarlivro.setMaximumSize(new java.awt.Dimension(100, 23));
        jBeditarlivro.setMinimumSize(new java.awt.Dimension(100, 23));
        jBeditarlivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeditarlivroActionPerformed(evt);
            }
        });

        jButton7.setText("Deletar Livro");
        jButton7.setMaximumSize(new java.awt.Dimension(100, 23));
        jButton7.setMinimumSize(new java.awt.Dimension(100, 23));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jBlistarlivro.setText("Listar Livro");
        jBlistarlivro.setMaximumSize(new java.awt.Dimension(100, 23));
        jBlistarlivro.setMinimumSize(new java.awt.Dimension(100, 23));
        jBlistarlivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlistarlivroActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 51, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Registrar Emprestimos");

        jBcadastrarEm.setText("Cadastrar Emprestimo");
        jBcadastrarEm.setMaximumSize(new java.awt.Dimension(100, 23));
        jBcadastrarEm.setMinimumSize(new java.awt.Dimension(100, 23));
        jBcadastrarEm.setPreferredSize(new java.awt.Dimension(140, 25));
        jBcadastrarEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarEmActionPerformed(evt);
            }
        });

        jBlistarem.setText("Listar");
        jBlistarem.setMaximumSize(new java.awt.Dimension(100, 23));
        jBlistarem.setMinimumSize(new java.awt.Dimension(100, 23));
        jBlistarem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlistaremActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBDeletarleitor, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jBeditarleitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBcadastrarleitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBlistarleitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBeditarlivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBcadastrarlivro, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jBlistarlivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(33, 33, 33)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBcadastrarEm, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBlistarem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(278, 278, 278))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(255, 255, 255))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBcadastrarlivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBcadastrarleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBlistarleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBeditarlivro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBlistarlivro, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jBeditarleitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBDeletarleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jBcadastrarEm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBlistarem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcadastrarleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarleitorActionPerformed
        // TODO add your handling code here:
            CadLeitor l = new CadLeitor();
        l.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        l.setVisible(true);
        l.show();
    }//GEN-LAST:event_jBcadastrarleitorActionPerformed

    private void jBlistarleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlistarleitorActionPerformed
        // TODO add your handling code here:
        ListarLeitor l = new ListarLeitor();
        l.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        l.setVisible(true);
        l.show();
    }//GEN-LAST:event_jBlistarleitorActionPerformed

    private void jBDeletarleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeletarleitorActionPerformed
        // TODO add your handling code here:
        DeletarLeitor l = new DeletarLeitor();
        l.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        l.setVisible(true);
        l.show();
    }//GEN-LAST:event_jBDeletarleitorActionPerformed

    private void jBeditarleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeditarleitorActionPerformed
              // TODO add your handling code here:
      EditarLeitor l = new EditarLeitor();
        l.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        l.setVisible(true);
      l.show();
    }//GEN-LAST:event_jBeditarleitorActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        DeletarLivro l = new DeletarLivro();
        l.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        l.setVisible(true);
        l.show();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jBlistarlivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlistarlivroActionPerformed
        ListarLivro l = new ListarLivro();
        l.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        l.setVisible(true);
        l.show();
    }//GEN-LAST:event_jBlistarlivroActionPerformed

    private void jBcadastrarlivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarlivroActionPerformed
        CadLivro l = new CadLivro();
        l.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        l.setVisible(true);
        l.show();
    }//GEN-LAST:event_jBcadastrarlivroActionPerformed

    private void jBeditarlivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeditarlivroActionPerformed
        EditarLivro l = new EditarLivro();
        l.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        l.setVisible(true);
        l.show();
    }//GEN-LAST:event_jBeditarlivroActionPerformed

    private void jBcadastrarEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarEmActionPerformed
        CadEmprestimos em = new CadEmprestimos();
        em.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        em.setVisible(true);
        em.show();
    }//GEN-LAST:event_jBcadastrarEmActionPerformed

    private void jBlistaremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlistaremActionPerformed
        ListarEmprestimo em= new ListarEmprestimo();
        em.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        em.setVisible(true);
        em.show();
    }//GEN-LAST:event_jBlistaremActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDeletarleitor;
    private javax.swing.JButton jBcadastrarEm;
    private javax.swing.JButton jBcadastrarleitor;
    private javax.swing.JButton jBcadastrarlivro;
    private javax.swing.JButton jBeditarleitor;
    private javax.swing.JButton jBeditarlivro;
    private javax.swing.JButton jBlistarem;
    private javax.swing.JButton jBlistarleitor;
    private javax.swing.JButton jBlistarlivro;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
